[tool.black]
line-length = 99
exclude = '''
(
    migrations
    | .mypy_cache
    | .pytest_cache
    | .tox
    | venv
)
'''
[tool.isort]
include_trailing_comma = true
line_length = 99
multi_line_output = 3