"""ユーザ設定"""
# スプレッドシート名
SPREADSHEET_NAME = "twitter管理シート"
# Twitter Api情報
TWITTER_API_KEY = ""
TWITTER_API_KEY_SECRET = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""
# TWITTER_BEARER_TOKEN = ""
# TWITTER_OAUTH2_CLIENT_ID = ""
# TWITTER_OAUTH2_CLIENT_SECRET = ""

# ツイートの順番：0:ランダム, 1:順次
TWITTER_ORDER = 0
